"""Self-contained HTML dashboard generator for codeassay."""

import json

from codeassay._chartjs import CHARTJS_MIN

DASHBOARD_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CodeAssay — {repo_name}</title>
<style>
  :root {{
    --bg: #0f172a; --surface: #1e293b; --border: #334155;
    --text: #e2e8f0; --text-muted: #94a3b8; --accent: #38bdf8;
    --green: #4ade80; --red: #f87171; --yellow: #fbbf24; --purple: #a78bfa;
    --orange: #fb923c; --pink: #f472b6; --teal: #2dd4bf;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
    background: var(--bg); color: var(--text); padding: 2rem;
    max-width: 1200px; margin: 0 auto;
  }}
  h1 {{ font-size: 1.5rem; margin-bottom: 0.25rem; }}
  .subtitle {{ color: var(--text-muted); font-size: 0.875rem; margin-bottom: 2rem; }}
  .cards {{
    display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem; margin-bottom: 2rem;
  }}
  .card {{
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 0.75rem; padding: 1.25rem;
  }}
  .card .label {{ color: var(--text-muted); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; }}
  .card .value {{ font-size: 2rem; font-weight: 700; margin-top: 0.25rem; }}
  .card .detail {{ color: var(--text-muted); font-size: 0.8rem; margin-top: 0.25rem; }}
  .charts {{
    display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; margin-bottom: 2rem;
  }}
  .chart-box {{
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 0.75rem; padding: 1.25rem;
  }}
  .chart-box h2 {{ font-size: 1rem; margin-bottom: 1rem; font-weight: 600; }}
  .chart-box.full {{ grid-column: 1 / -1; }}
  canvas {{ width: 100% !important; }}
  .footer {{
    text-align: center; color: var(--text-muted); font-size: 0.75rem;
    margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border);
  }}
  @media (max-width: 768px) {{
    .charts {{ grid-template-columns: 1fr; }}
    body {{ padding: 1rem; }}
  }}
</style>
</head>
<body>

<h1>CodeAssay — {repo_name}</h1>
<p class="subtitle">AI Code Quality Report &middot; {date}</p>

<div class="cards">
  <div class="card">
    <div class="label">AI Commit Rate</div>
    <div class="value" style="color: var(--accent)">{ai_commit_rate}%</div>
    <div class="detail">{ai_commit_count} of {total_commits} commits</div>
  </div>
  <div class="card">
    <div class="label">First-Pass Success</div>
    <div class="value" style="color: var(--green)">{first_pass_success_rate}%</div>
    <div class="detail">{first_pass_count} of {ai_commit_count} AI commits</div>
  </div>
  <div class="card">
    <div class="label">Rework Rate</div>
    <div class="value" style="color: var(--red)">{rework_rate}%</div>
    <div class="detail">{rework_count} rework events</div>
  </div>
  <div class="card">
    <div class="label">Mean Time to Rework</div>
    <div class="value" style="color: var(--yellow)">{mean_time_to_rework}h</div>
    <div class="detail">average hours to fix</div>
  </div>
</div>

<div class="charts">
  <div class="chart-box">
    <h2>Rework by Category</h2>
    <canvas id="categoryChart"></canvas>
  </div>
  <div class="chart-box">
    <h2>Rework by AI Tool</h2>
    <canvas id="toolChart"></canvas>
  </div>
  <div class="chart-box full">
    <h2>Trends Over Time</h2>
    <canvas id="trendChart" height="80"></canvas>
  </div>
  <div class="chart-box full">
    <h2>Top Rework Files</h2>
    <canvas id="filesChart" height="60"></canvas>
  </div>
</div>

<div class="footer">
  Generated by <strong>CodeAssay</strong> &middot; <a href="https://github.com/jeffsinason/codeassay" style="color: var(--accent)">github.com/jeffsinason/codeassay</a>
</div>

<script>{chartjs_source}</script>
<script>
const DATA = {data_json};

const COLORS = {{
  bug_fix: '#f87171', misunderstanding: '#a78bfa', test_failure: '#fbbf24',
  style_violation: '#38bdf8', security_issue: '#f472b6',
  incomplete_implementation: '#fb923c', over_engineering: '#2dd4bf',
  unclassified: '#64748b'
}};
const LABELS = {{
  bug_fix: 'Bug fix', misunderstanding: 'Misunderstanding', test_failure: 'Test failure',
  style_violation: 'Style/convention', security_issue: 'Security issue',
  incomplete_implementation: 'Incomplete', over_engineering: 'Over-engineering',
  unclassified: 'Unclassified'
}};

Chart.defaults.color = '#94a3b8';
Chart.defaults.borderColor = '#334155';

// Category doughnut
if (Object.keys(DATA.rework_by_category).length > 0) {{
  const cats = Object.entries(DATA.rework_by_category).sort((a,b) => b[1] - a[1]);
  const catTotal = cats.reduce((s, c) => s + c[1], 0);
  new Chart(document.getElementById('categoryChart'), {{
    type: 'doughnut',
    data: {{
      labels: cats.map(c => {{
        const pct = (c[1] / catTotal * 100).toFixed(1);
        return (LABELS[c[0]] || c[0]) + ' (' + pct + '%)';
      }}),
      datasets: [{{ data: cats.map(c => c[1]), backgroundColor: cats.map(c => COLORS[c[0]] || '#64748b') }}]
    }},
    options: {{
      plugins: {{
        legend: {{ position: 'right' }},
        tooltip: {{
          callbacks: {{
            label: function(ctx) {{
              const pct = (ctx.parsed / catTotal * 100).toFixed(1);
              return ctx.label.split(' (')[0] + ': ' + ctx.parsed + ' (' + pct + '%)';
            }}
          }}
        }}
      }}
    }}
  }});
}}

// Tool bar chart
if (Object.keys(DATA.rework_by_tool).length > 0) {{
  const tools = Object.entries(DATA.rework_by_tool).sort((a,b) => b[1] - a[1]);
  new Chart(document.getElementById('toolChart'), {{
    type: 'bar',
    data: {{
      labels: tools.map(t => t[0]),
      datasets: [{{ label: 'Rework Events', data: tools.map(t => t[1]), backgroundColor: '#a78bfa' }}]
    }},
    options: {{ plugins: {{ legend: {{ display: false }} }}, scales: {{ y: {{ beginAtZero: true, ticks: {{ stepSize: 1 }} }} }} }}
  }});
}}

// Trend line chart
if (DATA.trend.length > 0) {{
  new Chart(document.getElementById('trendChart'), {{
    type: 'line',
    data: {{
      labels: DATA.trend.map(t => t.month),
      datasets: [
        {{ label: 'AI Commits', data: DATA.trend.map(t => t.ai_commits), borderColor: '#38bdf8', backgroundColor: 'rgba(56,189,248,0.1)', fill: true, tension: 0.3 }},
        {{ label: 'Rework Events', data: DATA.trend.map(t => t.rework_events), borderColor: '#f87171', backgroundColor: 'rgba(248,113,113,0.1)', fill: true, tension: 0.3 }}
      ]
    }},
    options: {{ scales: {{ y: {{ beginAtZero: true }} }} }}
  }});
}}

// File hotspots horizontal bar
if (DATA.top_rework_files.length > 0) {{
  new Chart(document.getElementById('filesChart'), {{
    type: 'bar',
    data: {{
      labels: DATA.top_rework_files.map(f => f[0]),
      datasets: [{{ label: 'Rework Events', data: DATA.top_rework_files.map(f => f[1]), backgroundColor: '#fb923c' }}]
    }},
    options: {{ indexAxis: 'y', plugins: {{ legend: {{ display: false }} }}, scales: {{ x: {{ beginAtZero: true, ticks: {{ stepSize: 1 }} }} }} }}
  }});
}}
</script>
</body>
</html>"""


def generate_dashboard(metrics: dict, trend_data: list[dict], repo_name: str = "Repository") -> str:
    """Generate a self-contained HTML dashboard.

    Args:
        metrics: Output from compute_metrics()
        trend_data: Output from compute_trend_data()
        repo_name: Display name for the repo

    Returns:
        Complete HTML string
    """
    from datetime import datetime

    data_blob = {
        "rework_by_category": metrics["rework_by_category"],
        "rework_by_tool": metrics["rework_by_tool"],
        "top_rework_files": metrics["top_rework_files"],
        "trend": trend_data,
    }

    first_pass_count = metrics["ai_commit_count"] - metrics["reworked_commit_count"]

    return DASHBOARD_TEMPLATE.format(
        repo_name=repo_name,
        date=datetime.now().strftime("%Y-%m-%d"),
        ai_commit_rate=metrics["ai_commit_rate"],
        ai_commit_count=metrics["ai_commit_count"],
        total_commits=metrics["total_commits"],
        first_pass_success_rate=metrics["first_pass_success_rate"],
        first_pass_count=first_pass_count,
        rework_rate=metrics["rework_rate"],
        rework_count=metrics["rework_count"],
        mean_time_to_rework=metrics["mean_time_to_rework_hours"],
        chartjs_source=CHARTJS_MIN,
        data_json=json.dumps(data_blob),
    )
